version: '3.8'
networks:
  spring-microservices:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  postgres:
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: spring_practice
    depends_on:
      - kafka
    networks:
      - spring-microservices

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - spring-microservices

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - spring-microservices

  config-server:
    image: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8888 || exit 1"]
      start_period: 30s
    networks:
      - spring-microservices

  eureka-server:
    image: eureka-discovery
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8761 || exit 1"]
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - spring-microservices

  api-gateway:
    image: gateway-service
    ports:
      - "9000:9000"
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      user-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    networks:
      - spring-microservices

  user-service:
    image: user-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/spring_practice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8080 || exit 1"]
      start_period: 35s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - spring-microservices

  notification-service:
    image: notification-service
    restart: always
    ports:
      - "8081:8081"
    environment:
      SPRING_KAFKA_BOOTSTRAP-SERVERS: kafka:9092
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 8081 || exit 1"]
      start_period: 30s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    networks:
      - spring-microservices